Django/Book_Reviews/Book_Reviews/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.login.urls', namespace='login')),
    url(r'^books/', include('apps.review_books.urls', namespace='review_books')),
]

Django/Book_Reviews/apps/login/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.index),
    url(r'^register$', views.register),
    url(r'^login$', views.login),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^success$', views.success),
    url(r'^user/(?P<user_id>\d+)$', views.show)
]

Django/Book_Reviews/apps/review_books/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^add_book$', views.add_book, name="add"),
    url(r'^create', views.create, name="create"),
    url(r'^(?P<book_id>\d+)$', views.show),
    url(r'^(?P<book_id>\d+)/create$', views.create_additional)
]

Django/Book_Reviews/apps/review_books/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from ..login.models import User
from django.db import models


class Author(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(Author, related_name="books")
    def __str__(self):
        return self.title

class ReviewManager(models.Manager):
    def validate_review(self, post_data):
        errors = []

        if len(post_data['title']) < 1 or len(post_data['review']) < 1:
            errors.append('fields are required')
        if not "author" in post_data and len(post_data['new_author']) < 3:
            errors.append('new author names must 3 or more characters')

        if "author" in post_data and len(post_data['new_author']) > 0 and len(post_data['new_author']) < 3:
            errors.append('new author names must 3 or more characters')
        if not int(post_data['rating']) > 0 or not int(post_data['rating']) <= 5:
            errors.append('invalid rating')
        return errors

    def create_review(self, clean_data, user_id):
        # retrive or create author
        the_author = None
        if len(clean_data['new_author']) < 1:
            the_author = Author.objects.get(id=int(clean_data['author']))
        else:
            the_author = Author.objects.create(name=clean_data['new_author'])
        # retirive or create book
        the_book = None
        if not Book.objects.filter(title=clean_data['title']):
            the_book = Book.objects.create(
                title=clean_data['title'], author=the_author
            )
        else:
            the_book = Book.objects.get(title=clean_data['title'])
        # returns a Review object
        return self.create(
            review = clean_data['review'],
            rating = clean_data['rating'],
            book = the_book,
            reviewer = User.objects.get(id=user_id)
        )

    def recent_and_not(self):
        '''
        returns a tuple with the zeroeth index containing query for 3 most recent reviews, and the first index
        containing the rest
        '''
        return (self.all().order_by('-created_at')[:3], self.all().order_by('-created_at')[3:])

class Review(models.Model):
    review = models.TextField()
    rating = models.IntegerField()
    book = models.ForeignKey(Book, related_name="reviews")
    reviewer = models.ForeignKey(User, related_name="reviews_left")
    created_at = models.DateTimeField(auto_now_add=True)
    objects = ReviewManager()
    def __str__(self):
        return "Book: {}".format(self.book.title)

Django/Book_Reviews/apps/review_books/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from .models import Review, Author, Book, User
from django.shortcuts import render, redirect
from django.contrib import messages

# Create your views here.
def index(request):
    context = {
        'user': User.objects.get(id=request.session['user_id']),
        'recent': Review.objects.recent_and_not()[0],
        'more': Review.objects.recent_and_not()[1]
    }
    return render(request, 'review_books/index.html', context)

def add_book(request):
    context = {
        "authors": Author.objects.all()
    }
    return render(request, 'review_books/add.html', context)

def show(request, book_id):
    context = {
        'book': Book.objects.get(id=book_id)
    }
    return render(request, 'review_books/show.html', context)

def create(request):
    errs = Review.objects.validate_review(request.POST)
    if errs:
        for e in errs:
            messages.error(request, e)
    else:
        book_id = Review.objects.create_review(request.POST, request.session['user_id']).book.id
    return redirect('/books/{}'.format(book_id))

def create_additional(request, book_id):
    the_book = Book.objects.get(id=book_id)
    new_book_data = {
        'title': the_book.title,
        'author': the_book.author.id,
        'rating': request.POST['rating'],
        'review': request.POST['review'],
        'new_author': ''
    }
    errs = Review.objects.validate_review(new_book_data)
    if errs:
        for e in errs:
            messages.error(request, e)
    else:
        Review.objects.create_review(new_book_data, request.session['user_id'])
    return redirect('/books/' + book_id)

Django/Book_Reviews/apps/review_books/templates/review_books/add.html
<!DOCTYPE html>
<html>
    <head>
       <title>Add Book and Review</title>
       {% load staticfiles %}
       <link rel="stylesheet" href="{% static 'review_books/style.css' %}">
    </head>
    <body>
        <p class="home_logout">
            <a href="/books">Home</a> |
            <a href="/logout">Logout</a>
        </p>
        <h1>ADD A REVIEW</h1>
        <form class="left" action='/books/create' method='post'>{% csrf_token %}
            <p><label for="book_title">Book Title: <input type='text' name='title'></label></p>
            <p><label for="author">Author:</label></p>
            <p>
                <label class="small_text">Choose from the list: </label>
                <select class="" name="author">
                    {% for author in authors %}
                        <option value="{{ author.id }}">{{ author.name }}</option>
                    {% endfor %}
                </select>
            </p>
            <p>
                <label class="small_text" for="new_author">Or add a new author: <input type="text" name="new_author"></label>
            </p>
            <p>
                <label for="review">Review: <textarea name="review" rows="4" cols="40"></textarea></p></label>
            </p>
            <label for="rating"> Rating:
                <select class="" name="rating">
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
            </label>

            <p class="login_button"><input type='submit' value='Add Book and Review'></p>
        </form>
    </body>
</html>

Django/Book_Reviews/apps/review_books/templates/review_books/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load staticfiles %}
        <link href="{% static 'review_books/style.css' %}" rel="stylesheet">
    </head>
    <body>
        <header>
            <div class="messages">
                {% if messages %}
                    {% for message in messages %}
                        <p>{{ message }}</p>
                    {% endfor %}
                {% endif %}
            </div>
            <a href="{% url 'review_books:add' %}">Add book and review</a> | <a href="{% url 'login:logout' %}">Logout</a>
            <h2>Welcome, {{ user.first_name }}!</h2>
        </header>
        <div class="reviews">
            <h2>Recent Book Reviews:</h2>
            {% for review in recent %}
            <div class="reviews">
                <h2><a href="/books/{{review.book.id}}">{{ review.book.title }}</a></h2>
                <p>Rating: {{ review.rating }}</p>
                <p><a href="/user/{{review.reviewer.id}}">{{ review.reviewer.first_name}}</a> says: {{ review.review }}</p>
                <p>Posted on: {{ review.created_at }}</p>
            </div>
            {% endfor %}
        </div>
        <div class="reviews">
            <h3>Other Books with Reviews:</h3>
            {% for review in more %}
            <div class="review">
                <h2><a href="/books/{{review.book.id}}">{{ review.book.title }}</a></h2>
            </div>
            {% endfor %}
        </div>
    </body>
</html>

Django/Book_Reviews/apps/review_books/templates/review_books/show.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load staticfiles %}
        <link href="{% static 'review_books/style.css' %}" rel="stylesheet">
    </head>
    <body>
        <p class="home_logout"><a href="/books">Home</a> | <a href="/logout">Logout</a></p>
        <div class="info">
            <h1>{{book.title}}</h1>
            <h2>{{book.author}}</h2>
            <div class="reviews">
                <h3>Reviews:</h3>
                <hr>
                {% for review in book.reviews.all %}
                    <p>Rating: {{review.rating}}</p>
                    <p><a href="/user/{{review.reviewer.id}}">{{review.reviewer.name}}</a> says: {{review.review}}</p>
                <p>Posted on: {{review.created_at}}</p>
                <hr>
                {% endfor %}
            </div>
        </div>
        <form class="right" action="/books/{{book.id}}/create" method="POST">
            {% csrf_token %}
            <p>
                <label for="review">Review:</label>
                <textarea rows="5" cols="40" type="text" name="review"></textarea>
            </p>
            <p>
                <label for="rating">Rating</label>
                <select name="rating">
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
            </p>
            <p class="login_button"><input type="submit" value="Submit Review"></p>
        </form>
    </body>
</html>